# Generated by Django 5.2.7 on 2025-11-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_nickname"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_watch_users", "Can watch users"),
                    ("can_block_users", "Can block users"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
