# Generated by Django 5.2.8 on 2025-11-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
