# Generated by Django 5.2.7 on 2025-10-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="status",
            field=models.CharField(
                choices=[("ok", "Успешно"), ("nok", "Не успешно")],
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("active", "Запущена"),
                    ("stopped", "Завершена"),
                ],
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="timestamp_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время последней отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="timestamp_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата и время первой отправки"
            ),
        ),
    ]
