# Generated by Django 5.2.7 on 2025-11-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_attempt_status_alter_mailing_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="mailing/photo", verbose_name="Аватар"
            ),
        ),
    ]
