# Generated by Django 5.2.7 on 2025-11-18 20:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_attempt_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("email", "owner")},
        ),
    ]
