# Generated by Django 5.2.7 on 2025-11-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_client_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="attempt",
            field=models.ManyToManyField(
                to="mailing.client", verbose_name="Получатели"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(to="mailing.client", verbose_name="Клиенты"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("active", "Запущена"),
                    ("stopped", "Завершена"),
                ],
                default="created",
                verbose_name="Статус",
            ),
        ),
    ]
