# Generated by Django 5.2.7 on 2025-11-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0004_attempt_attempt_alter_mailing_clients_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attempt",
            old_name="attempt",
            new_name="recipient",
        ),
    ]
