# Generated by Django 5.2.7 on 2025-11-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_alter_client_unique_together_client_unique_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=100, verbose_name="Email"),
        ),
    ]
