# Generated by Django 5.2.7 on 2025-11-17 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0005_rename_attempt_attempt_recipient"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attempt",
            name="recipient",
        ),
        migrations.AddField(
            model_name="attempt",
            name="recipient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.client",
                verbose_name="Получатели",
            ),
            preserve_default=False,
        ),
    ]
