# Generated by Django 5.2.7 on 2025-11-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_alter_client_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["status"],
                "permissions": [("can_pause_mailing", "Can pause mailing")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("active", "Запущена"),
                    ("paused", "Остановлена"),
                    ("stopped", "Завершена"),
                ],
                default="created",
                verbose_name="Статус",
            ),
        ),
    ]
