# Generated by Django 5.2.7 on 2025-11-18 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_remove_attempt_recipient_attempt_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="mailing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing.mailing",
                verbose_name="Рассылка",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="recipient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mailing.client",
                verbose_name="Получатели",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mailings",
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
