# Generated by Django 5.2.7 on 2025-11-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_mailing_options_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["email"],
                "permissions": [("can_watch_clients", "Can watch clients")],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_watch_messages", "Can watch messages")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
